[SERVICE]
    Flush               30
    Daemon              Off
    Log_Level           ${FLUENT_BIT_LOG_LEVEL}
    Parsers_File        parsers.conf

[INPUT]
    Name                systemd
    Tag                 host.*
    Systemd_Filter_Type And
    Systemd_Filter      _SYSTEMD_UNIT=direct-nebula.service
    Systemd_Filter      _COMM=direct-nebula
    DB                  /var/log/fluent-bit/journald-cursor.sqlite

[OUTPUT]
    Name                datadog
    Match               *
    Host                http-intake.logs.datadoghq.com
    TLS                 on
    compress            gzip
    apikey              ${DATADOG_API_KEY_LOGGING}
    dd_service          nebula
    dd_source           nebula
    dd_message_key      log
    dd_tags             ${DATADOG_TAGS}

[FILTER]
    Name                parser
    Match               *
    Key_Name            MESSAGE
    Parser              json
